sudo: required

language: java
jdk: oraclejdk8

services:
  - docker

cache:
  directories:
  - "$HOME/.m2"

env:
  global:
  - secure: M2iQchJBi/Uxb0HT6Iq2Ehvm0pnbZtfuSDtlmBkDvxlCHrkVh9QNrCOqwqx3Pbv3j2c3aPQyvSg3depulDxjD/5hg0G/1EqeXb0hY1Y0aR4++6WVHaMuTRFd8NIbvbP1qFav5UHdecB8KnFiKC77GTdl+/H4PveNma8aVVqXZflBJAwffphX3pUsPOiyGsXaNRLxJdBmNhar+LOOG6NO2Z1zi0A7plEd7zyriQnH7nn/vKjo2lDDAGuwbPXza6yBcCAx9UZfFb2Evm1/vhgfY/EB/nxLNVgB5PIQaSpiiOtkyAgj4t3Nx7jC8mfv70rOu9tBJF8IBZ5Q3D6taFbTi5OnbeMfl5HHCGKVMktwVU2T9eoRPJsOdhKlwhA4UZOLSSKjr6oOEJ56Uag/ViED/xln0Hcl4xS3VJlLw88hfkZNnSOGAZglAo+RTlmfwOU7WIt950jhp5jNCNlWlVftWEcK+gJBAD+QcSVFsT73PYL+K08drFA2T523GiB0ECdLLXFxOwDf1B7sXwnx2j0eMyKLaY8JlUARsU28Xr1xPl5psQSTdtUf8D4SdG7GILYe75AlPT+G2KyUCu+uaL84JOdK7yNN71xAPo3jpisjwMAN+sT4Cw0jYwRflp5JJWNVI7/KjAse0Zh8g4zrBQJGvfQSP+dN8pBtHZQn5etU3Ww=
  - secure: by60N/6rjTMbC7xYqoxnoOfS2mpka1EUTgzIQJLufRnIC54JXs/ZYgoBFT1sbOgUFl/V5+Cew39jKN+ulWCM90OukVUzxQbKlsB6kB/vPxNAed3L7QYQMqEMKMjEiVFv+WGYXdI7qSub0yOoRMRdaF0DFFH2n0BQDsi1E/egWCGxh79KlDUp5Eq+4VV1EJzBk8HtR7MylKY4tQIvmJbad7ZPcU/W14ORd8EG1PvNfu13f5mjQ2UEvO30zTJvAkCkfLpFpIcYik3D3DcfKmOwUf7jKXW+ENfV8GdX4cjgpVIVexuVCJ9YW0kuTRr69Ey2Ck1r88WnqIm+GaH9ktgQbleWo3FAu5rKNh8sOadA/iTEUGwzVf+LiRfvzYJ4djOrnGeM9OOUEBbAJ16OiOr/1xqDDxxPLEfDDJPtzdQY1iDn+OiiTbfr5uPMMQfu3L5kIzuyAQKhS0mCoVyCWnJI4lD+H0sNnw0LkzQOBI7UbS0CwSAPDXdXvySxRAVoK/W1fV509LQ1EAV78e9NbNt/XOABdv1UF+SXLFBa4kEHW1bw8leboQA4DbxwjKlvDYZxtfcgH19Snaofvn7fOQTHy1MIwh0rIV8FeP6xxEYcbJy29lyoJdFBEDRhh124DPuQJeoQR2tSoGwaMKTVsgDDKDF6zNpc+h3FhFqjvNSeETo=
  - secure: BAEGSB5A3iEa1DqthPbB9c2LTycox/7Pq5nU1M5AlJMZ1RriXy6PsQ6/6X73IJX+89rAci1FC2mab/McmKSo89wg1fYyPnH4OfT8pL6UqtDrtBmBNQDl62SEDwQj9yLiYwWvHW9vvbY43N443CJxzPsh7fT7cuSzSHOsQczgbOhBYsondyTzTd51Q8Y7KudqhEyqCBbaDZk1SbnjJ8Mg24veMjaGOGKzQ3Ncbt3Y/AnNZXNgkD90DH56OjFnWjhHoAkwpAJXVRDVmh3ErUZ/2DsqwZcrki3fj4AkBes2UIqHI/NFXxzwboCGdlHmYhkCBngeC87Xe8q09jIEAQeabgVtyzqBjvQj0mcbtP5bEOZsVc1VE3GpLa9O/2OBXziY2+85WIt94YKiSYXZdSyB+o+QWm1c4Q1M9+gvjVvBwPHiCqyZMYWcW4xBx7UjizEI4KUtZYg95nLVqn3beGSeCJ7NpIItvhr76BplXPe9xqD/LoxheRz3IF6CXMTrA6Ig3DS8yxKtYiIpc18YMPGaIhNl1O8Q6+eSWc3xPoWFWi64voAWwqYJA0vmcO6UFflv9wBcp60TcTFJT3vpDb5rYtrm89xzvU6yd0Dm9EXIg8ez/uGYWY1W1JMOs4LnUrvtLTYRPZjDQ0tkiai+wA6d9Uvitg2xl4rKf6jqNUx8Bj8=

addons:
  sonarcloud:
    organization: sybrenapitest-org
    token:
      secure: "$SONAR_TOKEN"

script:
  - mvn clean install

after_script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push shboland/api:1.0.0
