sudo: required

language: java
jdk: oraclejdk8

services:
  - docker

cache:
  directories:
  - "$HOME/.m2"

addons:
  sonarcloud:
    organization: sybrenapitest-org
    token:
      secure: "eb21f40ecb59f211d58e51d1fea3f4516f73bfbc"

install:
  - mvn clean install

script:
  - sonar-scanner

after_script:
  - docker login -u shboland -p .widb-7e3Ndockerhub
  - docker push shboland/api:1.0.0

