sudo: required

language: java
jdk: oraclejdk8

services:
  - docker

cache:
  directories:
  - "$HOME/.m2"

env:
  global:

#addons:
#  sonarcloud:
#    organization: sybrenapitest-org
#    token:
#      secure: $SONAR_TOKEN

install:
  - mvn clean install

#script:
#  - sonar-scanner

after_script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push shboland/api:1.0.0

