sudo: required

language: java
jdk: oraclejdk8

cache:
  directories:
  - "$HOME/.m2"

env:
  global:

#addons:
#  sonarcloud:
#    organization: sybrenapitest-org
#    token:
#      secure: $SONAR_TOKEN

install:
  - mvn clean install

#script:
#  - sonar-scanner


